set(_CATKIN_CURRENT_PACKAGE "raven_2")
set(raven_2_VERSION "0.1.0")
set(raven_2_MAINTAINER "Todo <todo@todo.org>")
set(raven_2_PACKAGE_FORMAT "2")
set(raven_2_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "visualization_msgs" "tf" "dynamic_reconfigure")
set(raven_2_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "visualization_msgs" "tf" "dynamic_reconfigure")
set(raven_2_BUILDTOOL_DEPENDS "catkin")
set(raven_2_BUILDTOOL_EXPORT_DEPENDS )
set(raven_2_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "visualization_msgs" "tf" "dynamic_reconfigure")
set(raven_2_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "visualization_msgs" "tf" "dynamic_reconfigure")
set(raven_2_TEST_DEPENDS )
set(raven_2_DOC_DEPENDS "doxygen")
set(raven_2_DEPRECATED "")